name : python-ci

on : 
  push:
      branches : [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps : 
      - name : checkout code
        uses : actions/checkout@v4

      - name : install python 
        uses : actions/setup-python@v4
        with : 
            python-version: '3.11' 

      - name : Install dependencies
        run : pip install -r requirements.txt

      - name: Run a simple test
        run: python -c "import flask; print('Flask is installed âœ…')"
